package org.example.mall_tiny01.mbg.mapper;

import org.apache.ibatis.annotations.Param;
import org.example.mall_tiny01.dto.CartPromotionItem;
import org.example.mall_tiny01.mbg.model.OmsCartItem;

import java.util.List;

public interface OmsCartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cart_item
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cart_item
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(OmsCartItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cart_item
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(OmsCartItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cart_item
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    OmsCartItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cart_item
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(OmsCartItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cart_item
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(OmsCartItem row);

    int deleteByMemberId(@Param("memberId") Long memberId);

    int deleteBatch(@Param("ids") List<Long> ids);

    List<OmsCartItem> listByMemberId(@Param("memberId") Long memberId);

    List<CartPromotionItem> listPromotion(@Param("memberId") Long memberId, @Param("cartIds") List<Long> cartIds);
}