package org.example.mall_tiny01.mbg.mapper;

import org.apache.ibatis.annotations.Param;
import org.example.mall_tiny01.mbg.model.OmsOrderReturnApply;

import java.util.List;

public interface OmsOrderReturnApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(OmsOrderReturnApply row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(OmsOrderReturnApply row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    OmsOrderReturnApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(OmsOrderReturnApply row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_apply
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(OmsOrderReturnApply row);

    int deleteBatch(@Param("ids") List<Long> ids);

    List<OmsOrderReturnApply> list(@Param("id") Long id, @Param("status") Integer status,
                                   @Param("receiverKeyword") String receiverKeyword,
                                   @Param("handleMan") String handleMan,
                                   @Param("handleTime") String handleTime,
                                   @Param("createTime") String createTime);
}