package org.example.mall_tiny01.mbg.mapper;

import org.apache.ibatis.annotations.Param;
import org.example.mall_tiny01.mbg.model.OmsOrderReturnReason;

import java.util.List;

public interface OmsOrderReturnReasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_reason
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_reason
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(OmsOrderReturnReason row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_reason
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(OmsOrderReturnReason row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_reason
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    OmsOrderReturnReason selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_reason
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(OmsOrderReturnReason row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_return_reason
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(OmsOrderReturnReason row);

    int deleteBatch(@Param("ids") List<Long> ids);

    int updateStatus(@Param("ids") List<Long> ids, @Param("status") Integer status);

    List<OmsOrderReturnReason> list();
}