package org.example.mall_tiny01.mbg.mapper;

import org.apache.ibatis.annotations.Param;
import org.example.mall_tiny01.dto.SkuStockReduceDto;
import org.example.mall_tiny01.mbg.model.PmsSkuStock;

import java.util.List;

public interface PmsSkuStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(PmsSkuStock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(PmsSkuStock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    PmsSkuStock selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(PmsSkuStock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(PmsSkuStock row);
    int deleteByProductId(Long productId);

    List<PmsSkuStock> list(@Param("productId") Long productId, @Param("keyword") String keyword);

    /** 原子扣减库存（防超卖）：UPDATE stock = stock - #{quantity} WHERE id = #{skuId} AND stock >= #{quantity} */
    int updateStock(@Param("skuId") Long skuId, @Param("quantity") Integer quantity);

    /** 批量扣减库存（CASE WHEN 一条SQL完成，乐观锁防超卖） */
    int batchUpdateSkuStock(@Param("list") List<SkuStockReduceDto> list);
}