package org.example.mall_tiny01.mbg.mapper;

import org.apache.ibatis.annotations.Delete;
import org.example.mall_tiny01.mbg.model.SmsCouponProductCategoryRelation;

import java.util.List;

public interface SmsCouponProductCategoryRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_category_relation
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_category_relation
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(SmsCouponProductCategoryRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_category_relation
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(SmsCouponProductCategoryRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_category_relation
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    SmsCouponProductCategoryRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_category_relation
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(SmsCouponProductCategoryRelation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_product_category_relation
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(SmsCouponProductCategoryRelation row);

    void deleteByCouponId(Long id);

    List<SmsCouponProductCategoryRelation> selectByCouponId(Long couponId);
}