package org.example.mall_tiny01.mbg.mapper;

import org.example.mall_tiny01.mbg.model.SmsHomeRecommendSubject;
import org.apache.ibatis.annotations.Param;
import java.util.List;

public interface SmsHomeRecommendSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_subject
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_subject
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(SmsHomeRecommendSubject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_subject
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(SmsHomeRecommendSubject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_subject
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    SmsHomeRecommendSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_subject
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(SmsHomeRecommendSubject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_subject
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(SmsHomeRecommendSubject row);

    List<SmsHomeRecommendSubject> list(
        @Param("subjectName") String subjectName,
        @Param("recommendStatus") Integer recommendStatus
    );

    int updateRecommendStatus(@Param("ids") Long[] ids, @Param("recommendStatus") Integer recommendStatus);
}