package org.example.mall_tiny01.mbg.mapper;

import org.example.mall_tiny01.mbg.model.SmsHomeRecommendProduct;
import org.apache.ibatis.annotations.Param;
import java.util.List;

public interface SmsHomeRecommendProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(SmsHomeRecommendProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(SmsHomeRecommendProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    SmsHomeRecommendProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(SmsHomeRecommendProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_recommend_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(SmsHomeRecommendProduct row);

    List<SmsHomeRecommendProduct> list(
        @Param("productName") String productName,
        @Param("recommendStatus") Integer recommendStatus
    );

    int updateRecommendStatus(@Param("ids") Long[] ids, @Param("recommendStatus") Integer recommendStatus);
}