package org.example.mall_tiny01.mbg.mapper;

import org.example.mall_tiny01.mbg.model.SmsHomeNewProduct;
import org.apache.ibatis.annotations.Param;
import java.util.List;

public interface SmsHomeNewProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(SmsHomeNewProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(SmsHomeNewProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    SmsHomeNewProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(SmsHomeNewProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(SmsHomeNewProduct row);

    List<SmsHomeNewProduct> list(
        @Param("productName") String productName,
        @Param("recommendStatus") Integer recommendStatus
    );

    int updateRecommendStatus(@Param("ids") Long[] ids, @Param("recommendStatus") Integer recommendStatus);
}