package org.example.mall_tiny01.mbg.mapper;

import org.example.mall_tiny01.mbg.model.UmsAdminLoginLog;

public interface UmsAdminLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(UmsAdminLoginLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(UmsAdminLoginLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    UmsAdminLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(UmsAdminLoginLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(UmsAdminLoginLog row);
}