package org.example.mall_tiny01.mbg.mapper;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.example.mall_tiny01.mbg.model.UmsAdmin;
import org.example.mall_tiny01.mbg.model.UmsAdminLoginLog;
import org.example.mall_tiny01.mbg.model.UmsMenu;

import java.util.Date;
import java.util.List;

public interface UmsAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(UmsAdmin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(UmsAdmin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    UmsAdmin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(UmsAdmin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(UmsAdmin row);

    List<UmsAdmin> list(String keyword);

    @Insert("insert into ums_admin_role_relation (admin_id, role_id) values (#{adminId}, #{roleIds})")
    void updateRole(@Param("adminId") Long adminId, @Param("roleIds") Long roleIds);

    @Select("SELECT r.name FROM ums_role r INNER JOIN ums_admin_role_relation ar ON r.id = ar.role_id WHERE ar.admin_id = #{adminId}")
    String getRole(@Param("adminId") Long adminId);

    @Select("SELECT role_id FROM ums_admin_role_relation WHERE admin_id = #{adminId} LIMIT 1")
    Long getRoleId(@Param("adminId") Long adminId);

    @Select("SELECT sort FROM ums_role WHERE id = #{roleId}")
    Integer getSort(@Param("roleId") Long roleId);

    @Select("SELECT status FROM ums_role WHERE id = #{id}")
    Integer getStatus(@Param("id") Long id);

    @Select("SELECT description FROM ums_role WHERE id = #{id}")
    String getDescription(@Param("id") Long id);

    @Select("SELECT create_time FROM ums_admin WHERE id = #{adminId}")
    Date getCreateTime(@Param("adminId") Long adminId);

    @Select("SELECT COUNT(*) FROM ums_admin_role_relation WHERE role_id = #{id}")
    Integer getAdminCount(@Param("id") Long id);

    @Update("UPDATE ums_admin SET password = #{newPassword} WHERE username = #{username}")
    void updatePassword(@Param("username") String username, @Param("oldPassword") String oldPassword, @Param("newPassword") String newPassword);

    @Update("UPDATE ums_admin SET status = #{status} WHERE id = #{id}")
    void updateStatus(@Param("id") Long id, @Param("status") Integer status);

    @Select("SELECT password FROM ums_admin WHERE username = #{username}")
    String getPassword(@Param("username") String username);

    @Select("SELECT id FROM ums_admin WHERE username = #{username}")
    Long getAdminId(@Param("username") String username);

    @Insert("INSERT INTO ums_admin_login_log (admin_id, create_time, ip, address,user_agent) VALUES (#{adminId}, #{createTime}, #{ip}, #{address},#{userAgent})")
    void insertLoginLog(UmsAdminLoginLog umsAdminLoginLog);

    @Update("UPDATE ums_admin SET login_time = #{date} WHERE id = #{adminId}")
    void updateLoginTime(@Param("adminId") Long adminId, @Param("date") Date date);

    @Select("SELECT m.* FROM ums_menu m " +
            "INNER JOIN ums_role_menu_relation rm ON m.id = rm.menu_id " +
            "INNER JOIN ums_role r ON rm.role_id = r.id " +
            "WHERE r.name = #{role}")
    List<UmsMenu> getMenus(@Param("role") String role);

    @Select("SELECT icon FROM ums_admin WHERE id = #{adminId}")
    String getIcon(@Param("adminId") Long adminId);
}