package org.example.mall_tiny01.mbg.mapper;

import org.apache.ibatis.annotations.Param;
import org.example.mall_tiny01.mbg.model.UmsMember;

public interface UmsMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(UmsMember row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(UmsMember row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    UmsMember selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(UmsMember row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(UmsMember row);

    UmsMember selectByUsername(@Param("username") String username);

    UmsMember selectByPhone(@Param("phone") String phone);
}