package org.example.mall_tiny01.mbg.mapper;

import org.example.mall_tiny01.mbg.model.UmsMemberTag;

public interface UmsMemberTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(UmsMemberTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(UmsMemberTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    UmsMemberTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(UmsMemberTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_tag
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(UmsMemberTag row);
}