package org.example.mall_tiny01.mbg.mapper;

import org.example.mall_tiny01.mbg.model.UmsMemberLevel;
import org.apache.ibatis.annotations.Param;
import java.util.List;

public interface UmsMemberLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(UmsMemberLevel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(UmsMemberLevel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    UmsMemberLevel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(UmsMemberLevel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_level
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(UmsMemberLevel row);

    List<UmsMemberLevel> list(@Param("defaultStatus") Integer defaultStatus);
}