package org.example.mall_tiny01.mbg.mapper;

import org.example.mall_tiny01.mbg.model.UmsMemberTask;

public interface UmsMemberTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(UmsMemberTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(UmsMemberTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    UmsMemberTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(UmsMemberTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_task
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(UmsMemberTask row);
}