package org.example.mall_tiny01.mbg.mapper;

import org.example.mall_tiny01.mbg.model.UmsMemberRuleSetting;

public interface UmsMemberRuleSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(UmsMemberRuleSetting row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(UmsMemberRuleSetting row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    UmsMemberRuleSetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(UmsMemberRuleSetting row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_rule_setting
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(UmsMemberRuleSetting row);
}