package org.example.mall_tiny01.mbg.mapper;

import org.example.mall_tiny01.mbg.model.UmsMemberLoginLog;

public interface UmsMemberLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insert(UmsMemberLoginLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int insertSelective(UmsMemberLoginLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    UmsMemberLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKeySelective(UmsMemberLoginLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    int updateByPrimaryKey(UmsMemberLoginLog row);
}