package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class CmsSubject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.category_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.title
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.pic
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.product_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.recommend_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer recommendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.collect_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer collectCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.read_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.comment_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.album_pics
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String albumPics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.description
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.show_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer showStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.forward_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer forwardCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.category_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_subject.content
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_subject
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.id
     *
     * @return the value of cms_subject.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.id
     *
     * @param id the value for cms_subject.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.category_id
     *
     * @return the value of cms_subject.category_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.category_id
     *
     * @param categoryId the value for cms_subject.category_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.title
     *
     * @return the value of cms_subject.title
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.title
     *
     * @param title the value for cms_subject.title
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.pic
     *
     * @return the value of cms_subject.pic
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.pic
     *
     * @param pic the value for cms_subject.pic
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.product_count
     *
     * @return the value of cms_subject.product_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.product_count
     *
     * @param productCount the value for cms_subject.product_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.recommend_status
     *
     * @return the value of cms_subject.recommend_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getRecommendStatus() {
        return recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.recommend_status
     *
     * @param recommendStatus the value for cms_subject.recommend_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setRecommendStatus(Integer recommendStatus) {
        this.recommendStatus = recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.create_time
     *
     * @return the value of cms_subject.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.create_time
     *
     * @param createTime the value for cms_subject.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.collect_count
     *
     * @return the value of cms_subject.collect_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getCollectCount() {
        return collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.collect_count
     *
     * @param collectCount the value for cms_subject.collect_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCollectCount(Integer collectCount) {
        this.collectCount = collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.read_count
     *
     * @return the value of cms_subject.read_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.read_count
     *
     * @param readCount the value for cms_subject.read_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.comment_count
     *
     * @return the value of cms_subject.comment_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.comment_count
     *
     * @param commentCount the value for cms_subject.comment_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.album_pics
     *
     * @return the value of cms_subject.album_pics
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getAlbumPics() {
        return albumPics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.album_pics
     *
     * @param albumPics the value for cms_subject.album_pics
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setAlbumPics(String albumPics) {
        this.albumPics = albumPics == null ? null : albumPics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.description
     *
     * @return the value of cms_subject.description
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.description
     *
     * @param description the value for cms_subject.description
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.show_status
     *
     * @return the value of cms_subject.show_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.show_status
     *
     * @param showStatus the value for cms_subject.show_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.forward_count
     *
     * @return the value of cms_subject.forward_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getForwardCount() {
        return forwardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.forward_count
     *
     * @param forwardCount the value for cms_subject.forward_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setForwardCount(Integer forwardCount) {
        this.forwardCount = forwardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.category_name
     *
     * @return the value of cms_subject.category_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.category_name
     *
     * @param categoryName the value for cms_subject.category_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_subject.content
     *
     * @return the value of cms_subject.content
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_subject.content
     *
     * @param content the value for cms_subject.content
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}