package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class CmsTopicComment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic_comment.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic_comment.member_nick_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String memberNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic_comment.topic_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic_comment.member_icon
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String memberIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic_comment.content
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic_comment.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_topic_comment.show_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer showStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_topic_comment
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.id
     *
     * @return the value of cms_topic_comment.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.id
     *
     * @param id the value for cms_topic_comment.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.member_nick_name
     *
     * @return the value of cms_topic_comment.member_nick_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getMemberNickName() {
        return memberNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.member_nick_name
     *
     * @param memberNickName the value for cms_topic_comment.member_nick_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setMemberNickName(String memberNickName) {
        this.memberNickName = memberNickName == null ? null : memberNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.topic_id
     *
     * @return the value of cms_topic_comment.topic_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.topic_id
     *
     * @param topicId the value for cms_topic_comment.topic_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.member_icon
     *
     * @return the value of cms_topic_comment.member_icon
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getMemberIcon() {
        return memberIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.member_icon
     *
     * @param memberIcon the value for cms_topic_comment.member_icon
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setMemberIcon(String memberIcon) {
        this.memberIcon = memberIcon == null ? null : memberIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.content
     *
     * @return the value of cms_topic_comment.content
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.content
     *
     * @param content the value for cms_topic_comment.content
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.create_time
     *
     * @return the value of cms_topic_comment.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.create_time
     *
     * @param createTime the value for cms_topic_comment.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_topic_comment.show_status
     *
     * @return the value of cms_topic_comment.show_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_topic_comment.show_status
     *
     * @param showStatus the value for cms_topic_comment.show_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }
}