package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class PmsCommentReplay implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment_replay.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment_replay.comment_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment_replay.member_nick_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String memberNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment_replay.member_icon
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String memberIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment_replay.content
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment_replay.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment_replay.type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_comment_replay
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment_replay.id
     *
     * @return the value of pms_comment_replay.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment_replay.id
     *
     * @param id the value for pms_comment_replay.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment_replay.comment_id
     *
     * @return the value of pms_comment_replay.comment_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment_replay.comment_id
     *
     * @param commentId the value for pms_comment_replay.comment_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment_replay.member_nick_name
     *
     * @return the value of pms_comment_replay.member_nick_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getMemberNickName() {
        return memberNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment_replay.member_nick_name
     *
     * @param memberNickName the value for pms_comment_replay.member_nick_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setMemberNickName(String memberNickName) {
        this.memberNickName = memberNickName == null ? null : memberNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment_replay.member_icon
     *
     * @return the value of pms_comment_replay.member_icon
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getMemberIcon() {
        return memberIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment_replay.member_icon
     *
     * @param memberIcon the value for pms_comment_replay.member_icon
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setMemberIcon(String memberIcon) {
        this.memberIcon = memberIcon == null ? null : memberIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment_replay.content
     *
     * @return the value of pms_comment_replay.content
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment_replay.content
     *
     * @param content the value for pms_comment_replay.content
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment_replay.create_time
     *
     * @return the value of pms_comment_replay.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment_replay.create_time
     *
     * @param createTime the value for pms_comment_replay.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment_replay.type
     *
     * @return the value of pms_comment_replay.type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment_replay.type
     *
     * @param type the value for pms_comment_replay.type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setType(Integer type) {
        this.type = type;
    }
}