package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;

public class PmsProductAttribute implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.product_attribute_category_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long productAttributeCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.select_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer selectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.input_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer inputType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.input_list
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String inputList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.sort
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.filter_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer filterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.search_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer searchType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.related_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer relatedStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.hand_add_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer handAddStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute.type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_attribute
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.id
     *
     * @return the value of pms_product_attribute.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.id
     *
     * @param id the value for pms_product_attribute.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.product_attribute_category_id
     *
     * @return the value of pms_product_attribute.product_attribute_category_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getProductAttributeCategoryId() {
        return productAttributeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.product_attribute_category_id
     *
     * @param productAttributeCategoryId the value for pms_product_attribute.product_attribute_category_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setProductAttributeCategoryId(Long productAttributeCategoryId) {
        this.productAttributeCategoryId = productAttributeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.name
     *
     * @return the value of pms_product_attribute.name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.name
     *
     * @param name the value for pms_product_attribute.name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.select_type
     *
     * @return the value of pms_product_attribute.select_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getSelectType() {
        return selectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.select_type
     *
     * @param selectType the value for pms_product_attribute.select_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setSelectType(Integer selectType) {
        this.selectType = selectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.input_type
     *
     * @return the value of pms_product_attribute.input_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.input_type
     *
     * @param inputType the value for pms_product_attribute.input_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setInputType(Integer inputType) {
        this.inputType = inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.input_list
     *
     * @return the value of pms_product_attribute.input_list
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getInputList() {
        return inputList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.input_list
     *
     * @param inputList the value for pms_product_attribute.input_list
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setInputList(String inputList) {
        this.inputList = inputList == null ? null : inputList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.sort
     *
     * @return the value of pms_product_attribute.sort
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.sort
     *
     * @param sort the value for pms_product_attribute.sort
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.filter_type
     *
     * @return the value of pms_product_attribute.filter_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getFilterType() {
        return filterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.filter_type
     *
     * @param filterType the value for pms_product_attribute.filter_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setFilterType(Integer filterType) {
        this.filterType = filterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.search_type
     *
     * @return the value of pms_product_attribute.search_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getSearchType() {
        return searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.search_type
     *
     * @param searchType the value for pms_product_attribute.search_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setSearchType(Integer searchType) {
        this.searchType = searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.related_status
     *
     * @return the value of pms_product_attribute.related_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getRelatedStatus() {
        return relatedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.related_status
     *
     * @param relatedStatus the value for pms_product_attribute.related_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setRelatedStatus(Integer relatedStatus) {
        this.relatedStatus = relatedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.hand_add_status
     *
     * @return the value of pms_product_attribute.hand_add_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getHandAddStatus() {
        return handAddStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.hand_add_status
     *
     * @param handAddStatus the value for pms_product_attribute.hand_add_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setHandAddStatus(Integer handAddStatus) {
        this.handAddStatus = handAddStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute.type
     *
     * @return the value of pms_product_attribute.type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute.type
     *
     * @param type the value for pms_product_attribute.type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setType(Integer type) {
        this.type = type;
    }
}