package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;

public class PmsProductAttributeCategory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute_category.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute_category.name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute_category.attribute_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer attributeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_attribute_category.param_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer paramCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_attribute_category
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute_category.id
     *
     * @return the value of pms_product_attribute_category.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute_category.id
     *
     * @param id the value for pms_product_attribute_category.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute_category.name
     *
     * @return the value of pms_product_attribute_category.name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute_category.name
     *
     * @param name the value for pms_product_attribute_category.name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute_category.attribute_count
     *
     * @return the value of pms_product_attribute_category.attribute_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getAttributeCount() {
        return attributeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute_category.attribute_count
     *
     * @param attributeCount the value for pms_product_attribute_category.attribute_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setAttributeCount(Integer attributeCount) {
        this.attributeCount = attributeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_attribute_category.param_count
     *
     * @return the value of pms_product_attribute_category.param_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getParamCount() {
        return paramCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_attribute_category.param_count
     *
     * @param paramCount the value for pms_product_attribute_category.param_count
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setParamCount(Integer paramCount) {
        this.paramCount = paramCount;
    }
}