package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class PmsProductVertifyRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_vertify_record.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_vertify_record.product_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_vertify_record.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_vertify_record.vertify_man
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String vertifyMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_vertify_record.status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_product_vertify_record.detail
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pms_product_vertify_record
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_vertify_record.id
     *
     * @return the value of pms_product_vertify_record.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_vertify_record.id
     *
     * @param id the value for pms_product_vertify_record.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_vertify_record.product_id
     *
     * @return the value of pms_product_vertify_record.product_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_vertify_record.product_id
     *
     * @param productId the value for pms_product_vertify_record.product_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_vertify_record.create_time
     *
     * @return the value of pms_product_vertify_record.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_vertify_record.create_time
     *
     * @param createTime the value for pms_product_vertify_record.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_vertify_record.vertify_man
     *
     * @return the value of pms_product_vertify_record.vertify_man
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getVertifyMan() {
        return vertifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_vertify_record.vertify_man
     *
     * @param vertifyMan the value for pms_product_vertify_record.vertify_man
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setVertifyMan(String vertifyMan) {
        this.vertifyMan = vertifyMan == null ? null : vertifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_vertify_record.status
     *
     * @return the value of pms_product_vertify_record.status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_vertify_record.status
     *
     * @param status the value for pms_product_vertify_record.status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_product_vertify_record.detail
     *
     * @return the value of pms_product_vertify_record.detail
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_product_vertify_record.detail
     *
     * @param detail the value for pms_product_vertify_record.detail
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}