package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class SmsCouponHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.coupon_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.coupon_code
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String couponCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.member_nickname
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String memberNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.get_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer getType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.use_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer useStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.use_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Date useTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.order_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.order_sn
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.id
     *
     * @return the value of sms_coupon_history.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.id
     *
     * @param id the value for sms_coupon_history.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.coupon_id
     *
     * @return the value of sms_coupon_history.coupon_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.coupon_id
     *
     * @param couponId the value for sms_coupon_history.coupon_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.member_id
     *
     * @return the value of sms_coupon_history.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.member_id
     *
     * @param memberId the value for sms_coupon_history.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.coupon_code
     *
     * @return the value of sms_coupon_history.coupon_code
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getCouponCode() {
        return couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.coupon_code
     *
     * @param couponCode the value for sms_coupon_history.coupon_code
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode == null ? null : couponCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.member_nickname
     *
     * @return the value of sms_coupon_history.member_nickname
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getMemberNickname() {
        return memberNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.member_nickname
     *
     * @param memberNickname the value for sms_coupon_history.member_nickname
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setMemberNickname(String memberNickname) {
        this.memberNickname = memberNickname == null ? null : memberNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.get_type
     *
     * @return the value of sms_coupon_history.get_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getGetType() {
        return getType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.get_type
     *
     * @param getType the value for sms_coupon_history.get_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setGetType(Integer getType) {
        this.getType = getType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.create_time
     *
     * @return the value of sms_coupon_history.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.create_time
     *
     * @param createTime the value for sms_coupon_history.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.use_status
     *
     * @return the value of sms_coupon_history.use_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.use_status
     *
     * @param useStatus the value for sms_coupon_history.use_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setUseStatus(Integer useStatus) {
        this.useStatus = useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.use_time
     *
     * @return the value of sms_coupon_history.use_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.use_time
     *
     * @param useTime the value for sms_coupon_history.use_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.order_id
     *
     * @return the value of sms_coupon_history.order_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.order_id
     *
     * @param orderId the value for sms_coupon_history.order_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.order_sn
     *
     * @return the value of sms_coupon_history.order_sn
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.order_sn
     *
     * @param orderSn the value for sms_coupon_history.order_sn
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }
}