package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;

public class SmsHomeBrand implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_brand.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_brand.brand_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_brand.brand_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_brand.recommend_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer recommendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_brand.sort
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_home_brand
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_brand.id
     *
     * @return the value of sms_home_brand.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_brand.id
     *
     * @param id the value for sms_home_brand.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_brand.brand_id
     *
     * @return the value of sms_home_brand.brand_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_brand.brand_id
     *
     * @param brandId the value for sms_home_brand.brand_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_brand.brand_name
     *
     * @return the value of sms_home_brand.brand_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_brand.brand_name
     *
     * @param brandName the value for sms_home_brand.brand_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_brand.recommend_status
     *
     * @return the value of sms_home_brand.recommend_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getRecommendStatus() {
        return recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_brand.recommend_status
     *
     * @param recommendStatus the value for sms_home_brand.recommend_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setRecommendStatus(Integer recommendStatus) {
        this.recommendStatus = recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_brand.sort
     *
     * @return the value of sms_home_brand.sort
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_brand.sort
     *
     * @param sort the value for sms_home_brand.sort
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}