package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;

public class SmsHomeNewProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_new_product.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_new_product.product_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_new_product.product_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_new_product.recommend_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer recommendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_home_new_product.sort
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_home_new_product
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_new_product.id
     *
     * @return the value of sms_home_new_product.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_new_product.id
     *
     * @param id the value for sms_home_new_product.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_new_product.product_id
     *
     * @return the value of sms_home_new_product.product_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_new_product.product_id
     *
     * @param productId the value for sms_home_new_product.product_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_new_product.product_name
     *
     * @return the value of sms_home_new_product.product_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_new_product.product_name
     *
     * @param productName the value for sms_home_new_product.product_name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_new_product.recommend_status
     *
     * @return the value of sms_home_new_product.recommend_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getRecommendStatus() {
        return recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_new_product.recommend_status
     *
     * @param recommendStatus the value for sms_home_new_product.recommend_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setRecommendStatus(Integer recommendStatus) {
        this.recommendStatus = recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_home_new_product.sort
     *
     * @return the value of sms_home_new_product.sort
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_home_new_product.sort
     *
     * @param sort the value for sms_home_new_product.sort
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}