package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;

public class UmsAdminRoleRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_role_relation.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_role_relation.admin_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_role_relation.role_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_admin_role_relation
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_role_relation.id
     *
     * @return the value of ums_admin_role_relation.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_role_relation.id
     *
     * @param id the value for ums_admin_role_relation.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_role_relation.admin_id
     *
     * @return the value of ums_admin_role_relation.admin_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_role_relation.admin_id
     *
     * @param adminId the value for ums_admin_role_relation.admin_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_role_relation.role_id
     *
     * @return the value of ums_admin_role_relation.role_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_role_relation.role_id
     *
     * @param roleId the value for ums_admin_role_relation.role_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}