package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class UmsAdminLoginLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.admin_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.ip
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.address
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_admin_login_log.user_agent
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String userAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.id
     *
     * @return the value of ums_admin_login_log.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.id
     *
     * @param id the value for ums_admin_login_log.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.admin_id
     *
     * @return the value of ums_admin_login_log.admin_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.admin_id
     *
     * @param adminId the value for ums_admin_login_log.admin_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.create_time
     *
     * @return the value of ums_admin_login_log.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.create_time
     *
     * @param createTime the value for ums_admin_login_log.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.ip
     *
     * @return the value of ums_admin_login_log.ip
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.ip
     *
     * @param ip the value for ums_admin_login_log.ip
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.address
     *
     * @return the value of ums_admin_login_log.address
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.address
     *
     * @param address the value for ums_admin_login_log.address
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_admin_login_log.user_agent
     *
     * @return the value of ums_admin_login_log.user_agent
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_admin_login_log.user_agent
     *
     * @param userAgent the value for ums_admin_login_log.user_agent
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }
}