package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;

public class UmsIntegrationConsumeSetting implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_integration_consume_setting.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_integration_consume_setting.deduction_per_amount
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer deductionPerAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_integration_consume_setting.max_percent_per_order
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer maxPercentPerOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_integration_consume_setting.use_unit
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer useUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_integration_consume_setting.coupon_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer couponStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_integration_consume_setting
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_integration_consume_setting.id
     *
     * @return the value of ums_integration_consume_setting.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_integration_consume_setting.id
     *
     * @param id the value for ums_integration_consume_setting.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_integration_consume_setting.deduction_per_amount
     *
     * @return the value of ums_integration_consume_setting.deduction_per_amount
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getDeductionPerAmount() {
        return deductionPerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_integration_consume_setting.deduction_per_amount
     *
     * @param deductionPerAmount the value for ums_integration_consume_setting.deduction_per_amount
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setDeductionPerAmount(Integer deductionPerAmount) {
        this.deductionPerAmount = deductionPerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_integration_consume_setting.max_percent_per_order
     *
     * @return the value of ums_integration_consume_setting.max_percent_per_order
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getMaxPercentPerOrder() {
        return maxPercentPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_integration_consume_setting.max_percent_per_order
     *
     * @param maxPercentPerOrder the value for ums_integration_consume_setting.max_percent_per_order
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setMaxPercentPerOrder(Integer maxPercentPerOrder) {
        this.maxPercentPerOrder = maxPercentPerOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_integration_consume_setting.use_unit
     *
     * @return the value of ums_integration_consume_setting.use_unit
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getUseUnit() {
        return useUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_integration_consume_setting.use_unit
     *
     * @param useUnit the value for ums_integration_consume_setting.use_unit
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setUseUnit(Integer useUnit) {
        this.useUnit = useUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_integration_consume_setting.coupon_status
     *
     * @return the value of ums_integration_consume_setting.coupon_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getCouponStatus() {
        return couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_integration_consume_setting.coupon_status
     *
     * @param couponStatus the value for ums_integration_consume_setting.coupon_status
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCouponStatus(Integer couponStatus) {
        this.couponStatus = couponStatus;
    }
}