package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;

public class UmsMemberMemberTagRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_member_tag_relation.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_member_tag_relation.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_member_tag_relation.tag_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_member_member_tag_relation
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_member_tag_relation.id
     *
     * @return the value of ums_member_member_tag_relation.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_member_tag_relation.id
     *
     * @param id the value for ums_member_member_tag_relation.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_member_tag_relation.member_id
     *
     * @return the value of ums_member_member_tag_relation.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_member_tag_relation.member_id
     *
     * @param memberId the value for ums_member_member_tag_relation.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_member_tag_relation.tag_id
     *
     * @return the value of ums_member_member_tag_relation.tag_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_member_tag_relation.tag_id
     *
     * @param tagId the value for ums_member_member_tag_relation.tag_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}