package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;

public class UmsMemberProductCategoryRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_product_category_relation.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_product_category_relation.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_product_category_relation.product_category_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_member_product_category_relation
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_product_category_relation.id
     *
     * @return the value of ums_member_product_category_relation.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_product_category_relation.id
     *
     * @param id the value for ums_member_product_category_relation.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_product_category_relation.member_id
     *
     * @return the value of ums_member_product_category_relation.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_product_category_relation.member_id
     *
     * @param memberId the value for ums_member_product_category_relation.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_product_category_relation.product_category_id
     *
     * @return the value of ums_member_product_category_relation.product_category_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_product_category_relation.product_category_id
     *
     * @param productCategoryId the value for ums_member_product_category_relation.product_category_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }
}