package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class UmsMemberLoginLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_login_log.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_login_log.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_login_log.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_login_log.ip
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_login_log.city
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_login_log.login_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer loginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_login_log.province
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_member_login_log
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_login_log.id
     *
     * @return the value of ums_member_login_log.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_login_log.id
     *
     * @param id the value for ums_member_login_log.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_login_log.member_id
     *
     * @return the value of ums_member_login_log.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_login_log.member_id
     *
     * @param memberId the value for ums_member_login_log.member_id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_login_log.create_time
     *
     * @return the value of ums_member_login_log.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_login_log.create_time
     *
     * @param createTime the value for ums_member_login_log.create_time
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_login_log.ip
     *
     * @return the value of ums_member_login_log.ip
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_login_log.ip
     *
     * @param ip the value for ums_member_login_log.ip
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_login_log.city
     *
     * @return the value of ums_member_login_log.city
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_login_log.city
     *
     * @param city the value for ums_member_login_log.city
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_login_log.login_type
     *
     * @return the value of ums_member_login_log.login_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_login_log.login_type
     *
     * @param loginType the value for ums_member_login_log.login_type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setLoginType(Integer loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_login_log.province
     *
     * @return the value of ums_member_login_log.province
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_login_log.province
     *
     * @param province the value for ums_member_login_log.province
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }
}