package org.example.mall_tiny01.mbg.model;

import java.io.Serializable;

public class UmsMemberTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_task.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_task.name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_task.growth
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer growth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_task.intergration
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer intergration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_member_task.type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_member_task
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_task.id
     *
     * @return the value of ums_member_task.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_task.id
     *
     * @param id the value for ums_member_task.id
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_task.name
     *
     * @return the value of ums_member_task.name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_task.name
     *
     * @param name the value for ums_member_task.name
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_task.growth
     *
     * @return the value of ums_member_task.growth
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getGrowth() {
        return growth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_task.growth
     *
     * @param growth the value for ums_member_task.growth
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setGrowth(Integer growth) {
        this.growth = growth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_task.intergration
     *
     * @return the value of ums_member_task.intergration
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getIntergration() {
        return intergration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_task.intergration
     *
     * @param intergration the value for ums_member_task.intergration
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setIntergration(Integer intergration) {
        this.intergration = intergration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_member_task.type
     *
     * @return the value of ums_member_task.type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_member_task.type
     *
     * @param type the value for ums_member_task.type
     *
     * @mbg.generated Fri Apr 17 17:06:50 CST 2026
     */
    public void setType(Integer type) {
        this.type = type;
    }
}